### ISSUE TITLE
PHP Warning:  require(ugrsr.class.php): Failed to open stream: No such file or directory in /vqmod/install/index.php on line 44

### ISSUE THREAD

**Issue by chongshengdz** [vqmod/opencart#1]
PHP Warning:  require(ugrsr.class.php): Failed to open stream: No such file or directory in /vqmod/install/index.php on line 44

**Comment by JAY6390** [comment]
Which version of vqmod did you install specifically?

**Comment by chongshengdz** [comment]
> Which version of vqmod did you install specifically?

opencart 4.0, nothing work, please try to test it again and release a new version.

**Comment by JAY6390** [comment]
VQMod version, not opencart version. The file you need is this one
https://raw.githubusercontent.com/vqmod/vqmod/opencart/vqmod/install/ugrsr.class.php
and you just need to put that in the /vqmod/install/directory. It's in the latest release though so the issue is with something you've done, not the download

**Comment by JAY6390** [comment]
In fact, it looks like Qphoria has split the code completely. You will need to download the standard vqmod files and upload those too...
https://github.com/vqmod/vqmod/releases/tag/v2.6.7-stand-alone

**Comment by chongshengdz** [comment]
> VQMod version, not opencart version. The file you need is this one https://raw.githubusercontent.com/vqmod/vqmod/opencart/vqmod/install/ugrsr.class.php and you just need to put that in the `/vqmod/install/` directory. It's in the latest release though so the issue is with something you've done, not the download

install vqmod 2.6.6-opencart first and the replace files from [opencart-vqmod-scripts-v4.0.0] and then run install url again?

**Comment by JAY6390** [comment]
See my comment above. you need the files of vqmod v2.6.7 (stand alone) and then the files you've uploaded with the opencart specific scripts

**Comment by chongshengdz** [comment]
> See my comment above. you need the files of vqmod v2.6.7 (stand alone) and then the files you've uploaded with the opencart specific scripts

thanks, i was just installed and works fine now
